[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    -n 8
    --reruns 2
    --reruns-delay 2
    --html=reports/report.html
    --self-contained-html
    --alluredir=reports/allure-results
    --capture=no

markers =
    smoke: vital tests
    regression: full suite tests
